# Site settings
title: Allison Randolph Atwill
header-img: img/ocean_clouds_blue.jpg
email: allison.atwill@gmail.com
description: "An elegant blog using the Clean Blog template"
baseurl: "/allisonatwill.github.io"
url: "http://allisonatwill.github.io"
instagram_username: arandolpha
github_username:  allisonatwill
facebook_username:  Allison.Atwill

# Build settings
markdown: kramdown
parse_block_html: true
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
