# Site settings
title: a r a
long-title: Allison Randolph Atwill
header-img: img/ocean_clouds_blue.jpg
email: allison.atwill@gmail.com
description: "A blog by Allison Atwill"
baseurl: ""
url: "http://allisonatwill.github.io"
instagram_username: arandolpha
github_username:  allisonatwill
facebook_username:  Allison.Atwill
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-59746410-1'

# Build settings
markdown: kramdown
parse_block_html: true
comments: true
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
